### PR TITLE
Update main.cpp

### PR DESCRIPTION
**Pull request by alexmyczko**

### CODE REVIEW

**Comment by vog** [comment]
Would you mind creating a single pull request that contains all these changes?

Also, what is the motivation for these changes? That is, does it solve errors or warnings? Does it simplify our Makefile? Does it simplify other build scripts?

**Comment by alexmyczko** [comment]
I couldn't figure out how to do that in the github.com web interface. meanwhile i've just patched it and done a new updated debian package.

**Comment by vog** [comment]
No problem, I can also combine the changes.

But why are those changes needed for Debian? What's the downside of making use of the `-I/usr/include/SDL` flags as provided by `pkg-config --cflags sdl`?

Is there any Debian policy or generally accepted best practice that we are violating here?

**Comment by alexmyczko** [comment]
You're absolutely right, adding that PATH to Include directories would be easier to have it find the header files.

Are there any systems that have SDL.h not in /usr/include/SDL? if not so, just make it right in the header files, or in the Makefile. Currently I'm patching the includes:

https://sources.debian.org/patches/pushover/0.0.5+git20180420-2/

version -3 is already there with the segfault fixes, however it's in new queue (because of a new binary package shipping the music files as pushover-data)

Would be time for a 0.0.6 release?

**Comment by vog** [comment]
Our `Makefile` always calls `pkg-config --cflags sdl`. On any system I'm aware of, the output of that command contains:

    -I/usr/include/SDL

So the `/usr/include/SDL` header path is always be provided to `gcc` by our `Makefile` on any system. Do you have a system at hand where this is not the case?

Regarding the release: Yes, it is really time for the next release, which will be `1.0`.

**Pull request closed without merging**
